### ISSUE TITLE
SFML support

### ISSUE THREAD

**Issue by exilief** [Quent42340/OpenMiner#12]
Hey! I found this yesterday. A few days ago I started trying to improve [this Minecraft-like game](https://github.com/Hopson97/MineCraft-One-Week-Challenge), but then I decided to look at some other implementations first, and I gave yours a try. It looks very promising so far!
However, I don't really like SDL, so I made it support SFML (2.4+). I created a branch '[SFML-and-SDL](https://github.com/exilief/KubKraft/tree/SFML-and-SDL)', where I added a bunch of `#ifdef`s for all SDL code until it worked :D Now you can choose one with a global macro USE_SDL or USE_SFML. Of course it's not very nice having these ugly macros in some places, but it's not too bad I think.
So... is any of that helpful? xD I've seen in some places you kind of replicated some of the SFML classes (Vector2/3, Rect, ...) with the same names. Were you already planning to switch to SFML soon? I could now easily remove all SDL specific code to get a clean SFML version if you want, but there are some small problems with it still. With some more tricks I could also get rid of many of the macros I think, if you are interested in having both in one version. But it's probably a bad idea... I will probably make another branch 'SFML' and keep both updated with future commits, maybe they will be useful at some point.

Some general notes:
- OpenGL 2.1 (like stated in the readme) doesn't work for me. You are using glGenerateMipmap, which is available only since 3.0, and GL_QUADS, which is deprecated in >=3.1. So 3.0 is actually the only version that works at all (for me at least). So, to support <3.0 maybe generate mipmaps manually? Or replace GL_QUADS and say 3.0+?
- I'm not using GLEW, but [Glad](https://github.com/Dav1dde/glad) instead, so I added code to support the option USE_GLAD. GLEW is used by default instead.
- To make it compile with MinGW (GCC 7.2) I had to make some additions (not regarding SDL). I had to define M_PI in 2 places (maybe including cmath would work, but it's not defined by the standard anyway), and I had to include cstring twice, ctime once.
- All textures (except the top face of stone) look really horrible with weird artifacts, like my screen was broken. Is this because of a recent commit you still have to fix? Or do only I have that? It's with SFML and SDL. Maybe I messed something up? Will try with master branch later.
- Also, the furnace smelting isn't working for me (lighting up, but not smelting).

**Comment by Quent42340** [comment]
I finally decided to drop SDL and to use SFML instead.

I'm currently thinking of big design changes:
- Client/server architecture (I kinda like the SFML network module)
- Lua modding API

Thus, I'm currently working on the Lua API and its integration within the game.
So since the project revived, your PRs for the SFML changes are welcome now. :)

**Comment by exilief** [comment]
Oh, great! Sorry I just saw this now.

Okay, my branch SFML already has working replacements for all the important SDL stuff. There were direct counterparts for most classes, so it was quite straightforward to do. Some things don't quite work the same but should be ok, I added some comments. I also created the branch SFML-2 with some small tweaks and I added conversion functions between your Rect/Vector/Color classes and the sf::Rect/sf::... versions. But because SFML already has those classes, you'll probably want to use those from now on, right?
So, you probably need to clean it up a bit, but should I make a PR for the SFML-2 branch now?
The problem is, I never properly learned Git and don't know how to take the commits you've made since and apply them to my branch... can you figure that out? :)

About networking: I've read that SFML's network module is a bit simplistic and doesn't offer much. It's probably a good start, but might need some extra work later, but it also might be fine, not sure :D
If you need more features maybe check [SFNUL](https://github.com/binary1248/SFNUL) out, with more information [here](https://en.sfml-dev.org/forums/index.php?topic=13723.0). It was made by an SFML dev and is based on it.

**Comment by exilief** [comment]
Okay, I did rebase as you suggested. It took me a while, but I think I did it correctly. I hope I didn't mess anything up.

The SDL code is already removed, I only had some commented out files left that are deleted now.

I have made a PR now. I hope everything makes sense and you can make use of it :)

**Comment by Quent42340** [comment]
Thanks for your work. :+1:

**Comment by exilief** [comment]
You're welcome!
