### ISSUE TITLE
Flicker in some video cards

### ISSUE THREAD

**Issue by pgimeno** [Quent42340/OpenMiner#23]
As discussed in IRC, there is a problem in some video cards that causes a flicker very similar to Z-fighting in lighting, leaves and grass.

I've managed to fix it with the following patch:

```diff
diff --git a/resources/shaders/game.f.glsl b/resources/shaders/game.f.glsl
index 2858f63..bd29b6d 100644
--- a/resources/shaders/game.f.glsl
+++ b/resources/shaders/game.f.glsl
@@ -20,19 +20,23 @@ vec4 light(vec4 color, vec3 lightColor, vec4 lightPosition, float ambientIntensi
 vec4 fog(vec4 color, float fogCoord, float fogStart, float fogEnd);
 
 void main() {
+	float blockID = floor(v_blockID + 0.5);
+	float blockFace = floor(v_blockFace + 0.5);
+	float lightCheck = floor(v_lightValue.x + 0.5);
+
 	// Discard if the pixel is too far away
-	if(v_blockID != -1 && v_dist > u_renderDistance) discard;
+	if(blockID != -1. && v_dist > u_renderDistance) discard;
 
 	vec4 color = getColor();
-	if (v_blockID == 8) { // Water
+	if (blockID == 8.) { // Water
 		color.a = 0.85;
 	}
-	else if (v_blockID == 4) { // Leaves
+	else if (blockID == 4.) { // Leaves
 		color += vec4(-0.5, -0.15, -0.4, 0);
 		/* if (v_dist > 20 && color.a == 0) */
 		/* 	color.a = 0.5; */
 	}
-	else if (v_blockID == 3) { // Grass
+	else if (blockID == 3.) { // Grass
 		if (color.r == color.g && color.r == color.b) {
 			color += vec4(-0.3, -0.1, -0.25, 0);
 			/* color += vec4(-0.4, -0.15, -0.3, 0); */
@@ -40,7 +44,7 @@ void main() {
 	}
 
 	// Very cheap "transparency": don't draw pixels with a low alpha value
-	if(color.a < 0.3 && v_blockID != -1) discard;
+	if(color.a < 0.3 && blockID != -1.) discard;
 
 	// FIXME: FINISH THIS WITH PROPER CODE AND SUN BASIC DISPLAY
 	// int maxTime = 5 * 1000;
@@ -49,18 +53,18 @@ void main() {
 	// color *= light(vec3(1.0, 1.0, 1.0), vec4(lightPosition, 1.0), 0.5, 0.5);
 
 	float minBrightness = 2.0 / 16.0;
-	if (v_lightValue.x != -1) {
+	if (lightCheck != -1.) {
 		float ambientIntensity = max(max(v_lightValue.x, v_lightValue.y) / 16.0, minBrightness);
 		float diffuseIntensity = max(v_lightValue.x, v_lightValue.y) / 32.0;
 
 		// Bottom
-		if (v_blockFace == 2)
+		if (blockFace == 2.)
 			ambientIntensity = max(ambientIntensity * 0.6, minBrightness);
 		// Left or Right
-		if (v_blockFace == 0 || v_blockFace == 1)
+		if (blockFace == 0. || blockFace == 1.)
 			ambientIntensity = max(ambientIntensity * 0.75, minBrightness);
 		// Front or Back
-		if (v_blockFace == 4 || v_blockFace == 5)
+		if (blockFace == 4. || blockFace == 5.)
 			ambientIntensity = max(ambientIntensity * 0.9, minBrightness);
 
 		color = light(color, vec3(1.0, 1.0, 1.0), v_coord3d, ambientIntensity, diffuseIntensity);
```

The patch hints at the cause: the values of the floating-point variables are not always exactly equal to the integer value they are compared with. I believe this is caused by interpolation between vertices, which may be inexact depending on the implementation. For example, this interpolation formula is not monotonic: `a*(1-t)+b*t`; e.g. when `a = b = 3` and `t = 0.2`, in Python (with double precision floats):

```
>>> 3 * (1 - 0.2) + 3 * 0.2
3.0000000000000004
```

**Comment by Quent42340** [comment]
So you're rounding values to the nearest integer? Interesting

Why do you need to compare with floats then?

Btw, I guess you don't want to use PRs on GitHub since you gave me this patch?
I have a self-hosted Gogs here: http://git.gnidmoo.tk (which is currently down, but will come back this weekend)
Would you be ok to do PRs there instead of sending me patches?

Anyway, I'll merge this patch soon. :+1:

**Comment by pgimeno** [comment]
> Why do you need to compare with floats then?

Lack of background, basically. I've started with GL/GLSL very recently, and I'm still not very sure about what types are supported by what versions. I seem to remember that integer support was a late addition to GLSL, therefore I've avoided integer variables and literals, and used floats instead just to be safe (perhaps too much).

I also know for a fact that some implementations don't accept integers where floats are expected (at least without an explicit typecast), and the signature of the floor function is:

```
float floor(float x)
```

This is where I learned about the int to float implicit conversion issues:

https://love2d.org/forums/viewtopic.php?p=203077#p203077

> Would you be ok to do PRs there instead of sending me patches?

Yes. I am going to delete my MSGitHub account soon after Minetest 5 is out, and I don't want to create any forks at this point, but I'm OK with using other git hosts like a self-hosted Gogs. Better even if it's possible to submit issues there.

**Comment by Quent42340** [comment]
> Yes. I am going to delete my MSGitHub account soon after Minetest 5 is out, and I don't want to create any forks at this point, but I'm OK with using other git hosts like a self-hosted Gogs. Better even if it's possible to submit issues there.

I created the repo: http://git.gnidmoo.tk/gnidmoo/OpenMiner

You can open issues and PRs there. Be warned though, this is a very old server that I never configured to use HTTPS, so be sure to use a randomly generated password that you don't use somewhere else.
